project_id = "gqkfbxhuijpfcnjimlfj"

[functions.stripe-webhook]
verify_jwt = false

[functions.create-setup-intent]
verify_jwt = true

[functions.create-checkout]
verify_jwt = true

[functions.create-checkout-public]
verify_jwt = false

[functions.check-trial-eligibility]
verify_jwt = false

[functions.get-billing-history]
verify_jwt = true