-- Final batch of Year 2-3 curriculum questions
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y3FR003', 'Number - Fractions', 'Add and subtract fractions with the same denominator within one whole', 'Calculate: 5/7 - 2/7', 'Multiple Choice', '["3/7", "3/14", "7/7", "2/7"]', '3/7', 'Medium', ARRAY['Fractions_DenominatorOperation'], 'Student may incorrectly operate on denominators.', 'Year 3: Subtracting fractions with same denominator.', 'year 2-3'),
('Y3FR004', 'Number - Fractions', 'Compare and order unit fractions, and fractions with the same denominators', 'Which is larger: 1/3 or 1/5?', 'Multiple Choice', '["1/3", "1/5", "They are equal", "Cannot tell"]', '1/3', 'Hard', ARRAY['UnitFraction_DenominatorConfusion'], 'Student may think larger denominator means larger fraction.', 'Year 3: Comparing unit fractions.', 'year 2-3'),
('Y2ME001', 'Measurement', 'Choose and use appropriate standard units to estimate and measure length/height', 'Which unit would you use to measure the length of a pencil?', 'Multiple Choice', '["centimetres", "metres", "kilometres", "hours"]', 'centimetres', 'Easy', ARRAY['Unit_InappropriateChoice'], 'Student may choose an inappropriate unit like metres for small objects.', 'Year 2: Choosing appropriate measurement units.', 'year 2-3'),
('Y2ME002', 'Measurement', 'Recognise and use symbols for pounds (£) and pence (p)', 'How much money is £2 and 50p altogether?', 'Multiple Choice', '["£2.50", "£2.05", "£52", "£250"]', '£2.50', 'Medium', ARRAY['Money_DecimalPlacement'], 'Student may write £2.05 instead of £2.50 for 50p.', 'Year 2: Combining pounds and pence.', 'year 2-3'),
('Y2ME003', 'Measurement', 'Tell and write the time to five minutes, including quarter past/to', 'What time is quarter past 3?', 'Multiple Choice', '["3:15", "3:45", "3:30", "3:05"]', '3:15', 'Medium', ARRAY['Time_QuarterConfusion'], 'Student may confuse quarter past with quarter to (3:45).', 'Year 2: Understanding quarter past notation.', 'year 2-3'),
('Y3ME001', 'Measurement', 'Measure, compare, add and subtract: lengths (m/cm/mm)', 'How many millimetres are in 3 centimetres?', 'Multiple Choice', '["30", "3", "300", "10"]', '30', 'Medium', ARRAY['Conversion_FactorError'], 'Student may use wrong conversion factor or forget to multiply.', 'Year 3: Converting between metric units.', 'year 2-3'),
('Y3ME002', 'Measurement', 'Measure the perimeter of simple 2-D shapes', 'A square has sides of 5cm. What is its perimeter?', 'Multiple Choice', '["20cm", "25cm", "10cm", "15cm"]', '20cm', 'Medium', ARRAY['Perimeter_AreaConfusion'], 'Student may calculate area (25cm²) instead of perimeter.', 'Year 3: Calculating perimeter of regular shapes.', 'year 2-3'),
('Y3ME003', 'Measurement', 'Tell and write the time from an analogue clock, including using Roman numerals', 'A clock shows the Roman numeral IX. What number is this?', 'Multiple Choice', '["9", "11", "4", "6"]', '9', 'Medium', ARRAY['RomanNumerals_AdditionError'], 'Student may add I and X (1+10=11) instead of subtracting.', 'Year 3: Reading Roman numerals on clocks.', 'year 2-3'),
('Y3ME004', 'Measurement', 'Add and subtract amounts of money to give change', 'You buy a toy for £3.45 and pay with £5. How much change do you get?', 'Multiple Choice', '["£1.55", "£2.55", "£1.45", "£8.45"]', '£1.55', 'Hard', ARRAY['Money_SubtractionError'], 'Student may make errors when subtracting with decimals.', 'Year 3: Calculating change with money.', 'year 2-3'),
('Y2GS001', 'Geometry - Properties of Shapes', 'Identify and describe properties of 2-D shapes, including number of sides', 'How many sides does a triangle have?', 'Multiple Choice', '["3", "4", "5", "6"]', '3', 'Easy', NULL, NULL, 'Year 2: Basic shape property identification.', 'year 2-3');