-- Import Year 4-5 curriculum questions from provided JSON
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y4NPV001', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count on in 25s from 150. What comes next: 150, 175, 200, __?', 'Multiple Choice', '["225", "250", "215", "300"]', '225', 'Easy', NULL, NULL, 'Year 4: Skip counting by 25s.', 'year 4-5'),
('Y4NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What is the value of the digit 7 in the number 3,746?', 'Multiple Choice', '["700", "7", "70", "7000"]', '700', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify the wrong place value position (70 for tens or 7 for ones).', 'Year 4: Understanding hundreds place in 4-digit numbers.', 'year 4-5'),
('Y4NPV003', 'Number - Number and Place Value', 'Count backwards through zero to include negative numbers', 'Continue the sequence: 3, 1, -1, __', 'Multiple Choice', '["-3", "-2", "0", "-4"]', '-3', 'Medium', ARRAY['NegativeNumbers_PatternError'], 'Student may not recognize the pattern of subtracting 2 each time.', 'Year 4: Counting backwards through zero.', 'year 4-5'),
('Y4NPV004', 'Number - Number and Place Value', 'Round any number to the nearest 10, 100 or 1000', 'Round 4,567 to the nearest hundred.', 'Multiple Choice', '["4,600", "4,500", "4,570", "5,000"]', '4,600', 'Medium', ARRAY['Rounding_DirectionError'], 'Student may round down to 4,500 instead of up to 4,600.', 'Year 4: Rounding to nearest hundred.', 'year 4-5'),
('Y5NPV001', 'Number - Number and Place Value', 'Read, write, order and compare numbers to at least 1,000,000', 'Which number is larger: 456,789 or 456,879?', 'Multiple Choice', '["456,879", "456,789", "They are equal", "Cannot tell"]', '456,879', 'Medium', ARRAY['LargeNumber_DigitPositionError'], 'Student may compare wrong place values in large numbers.', 'Year 5: Comparing 6-digit numbers.', 'year 4-5'),
('Y5NPV002', 'Number - Number and Place Value', 'Count forwards or backwards in steps of powers of 10', 'What is 34,500 + 1,000?', 'Multiple Choice', '["35,500", "34,600", "44,500", "34,510"]', '35,500', 'Easy', ARRAY['PowersOf10_PlaceValueError'], 'Student may add to wrong place value column.', 'Year 5: Adding powers of 10.', 'year 4-5'),
('Y5NPV003', 'Number - Number and Place Value', 'Interpret negative numbers in context, count forwards and backwards with positive and negative whole numbers', 'The temperature is -5°C. It rises by 8°C. What is the new temperature?', 'Multiple Choice', '["3°C", "-13°C", "13°C", "-3°C"]', '3°C', 'Medium', ARRAY['NegativeNumbers_OperationError'], 'Student may subtract instead of add (-5-8=-13) or mishandle crossing zero.', 'Year 5: Working with negative numbers in context.', 'year 4-5'),
('Y5NPV004', 'Number - Number and Place Value', 'Round any number up to 1,000,000 to the nearest 10, 100, 1000, 10,000 and 100,000', 'Round 654,321 to the nearest 10,000.', 'Multiple Choice', '["650,000", "660,000", "654,000", "700,000"]', '650,000', 'Hard', ARRAY['Rounding_LargePlaceValue'], 'Student may round to wrong place value or round up incorrectly.', 'Year 5: Rounding large numbers to ten thousands.', 'year 4-5'),
('Y4ASM001', 'Number - Addition and Subtraction', 'Add and subtract numbers with up to 4 digits using formal written methods', 'Calculate: 3,456 + 1,789', 'Multiple Choice', '["5,245", "4,245", "5,235", "5,145"]', '5,245', 'Medium', ARRAY['Addition_CarryingError'], 'Student may make errors when carrying over between columns.', 'Year 4: 4-digit addition with carrying.', 'year 4-5'),
('Y4ASM002', 'Number - Addition and Subtraction', 'Solve addition and subtraction two-step problems in contexts', 'A school had 1,234 books. They bought 256 more books and then gave away 189 books. How many books do they have now?', 'Multiple Choice', '["1,301", "1,679", "1,290", "1,401"]', '1,301', 'Hard', ARRAY['MultiStep_SequenceError'], 'Student may add all numbers (1,679) instead of adding then subtracting.', 'Year 4: Two-step word problem with addition and subtraction.', 'year 4-5');