-- Continue importing the remaining Year 2-3 curriculum questions
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y3ASM003', 'Number - Addition and Subtraction', 'Solve problems, including missing number problems', '__ + 45 = 82. What is the missing number?', 'Multiple Choice', '["37", "127", "47", "27"]', '37', 'Medium', ARRAY['MissingNumber_OperationError'], 'Student may add instead of subtract (45+82=127).', 'Year 3: Inverse operations for missing numbers.', 'year 2-3'),
('Y2MD001', 'Number - Multiplication and Division', 'Recall and use multiplication and division facts for the 2, 5 and 10 multiplication tables', 'What is 5 × 4?', 'Multiple Choice', '["20", "9", "15", "25"]', '20', 'Easy', ARRAY['Multiplication_AdditionConfusion'], 'Student may add instead of multiply (5+4=9).', 'Year 2: Basic multiplication fact from 5 times table.', 'year 2-3'),
('Y2MD002', 'Number - Multiplication and Division', 'Solve problems involving multiplication and division, using arrays', 'There are 3 rows of apples with 5 apples in each row. How many apples are there altogether?', 'Multiple Choice', '["15", "8", "12", "20"]', '15', 'Medium', ARRAY['Array_AdditionError'], 'Student may add rows and items (3+5=8) instead of multiplying.', 'Year 2: Array representation of multiplication.', 'year 2-3'),
('Y3MD001', 'Number - Multiplication and Division', 'Recall and use multiplication and division facts for the 3, 4 and 8 multiplication tables', 'What is 8 × 3?', 'Multiple Choice', '["24", "21", "32", "11"]', '24', 'Medium', ARRAY['Multiplication_NearbyFact'], 'Student may confuse with 7×3=21 or add 8+3=11.', 'Year 3: Multiplication facts for 8 times table.', 'year 2-3'),
('Y3MD002', 'Number - Multiplication and Division', 'Write and calculate mathematical statements for multiplication using the tables they know', 'Calculate: 4 × 12', 'Multiple Choice', '["48", "16", "44", "52"]', '48', 'Hard', ARRAY['Multiplication_PartialProduct'], 'Student may only multiply 4×2=8 and miss the tens.', 'Year 3: Two-digit multiplication using known facts.', 'year 2-3'),
('Y3MD003', 'Number - Multiplication and Division', 'Solve problems, including positive integer scaling problems', 'Tom has 5 marbles. Sam has 3 times as many. How many marbles does Sam have?', 'Multiple Choice', '["15", "8", "3", "20"]', '15', 'Medium', ARRAY['Scaling_AdditionError'], 'Student may add instead of multiply (5+3=8).', 'Year 3: Understanding scaling in word problems.', 'year 2-3'),
('Y2FR001', 'Number - Fractions', 'Recognise, find, name and write fractions 1/3, 1/4, 2/4 and 3/4', 'What fraction of this shape is shaded? [Imagine a rectangle divided into 4 equal parts with 3 parts shaded]', 'Multiple Choice', '["3/4", "1/4", "1/3", "4/3"]', '3/4', 'Medium', ARRAY['Fraction_InvertedReading'], 'Student may confuse numerator and denominator positions.', 'Year 2: Visual fraction identification.', 'year 2-3'),
('Y2FR002', 'Number - Fractions', 'Write simple fractions and recognise equivalence', 'Which fraction is the same as 1/2?', 'Multiple Choice', '["2/4", "1/4", "3/4", "1/3"]', '2/4', 'Hard', ARRAY['Equivalence_NotRecognized'], 'Student may not recognize that 2/4 equals 1/2.', 'Year 2: Basic equivalent fractions.', 'year 2-3'),
('Y3FR001', 'Number - Fractions', 'Count up and down in tenths', 'What is 3/10 + 2/10?', 'Multiple Choice', '["5/10", "5/20", "1/10", "6/10"]', '5/10', 'Easy', ARRAY['Fractions_DenominatorAddition'], 'Student may incorrectly add denominators (10+10=20).', 'Year 3: Adding tenths.', 'year 2-3'),
('Y3FR002', 'Number - Fractions', 'Recognise and show, using diagrams, equivalent fractions with small denominators', 'Which fraction is equivalent to 2/3?', 'Multiple Choice', '["4/6", "2/6", "3/4", "1/3"]', '4/6', 'Medium', ARRAY['Equivalence_ScalingError'], 'Student may not scale both numerator and denominator correctly.', 'Year 3: Finding equivalent fractions.', 'year 2-3');