-- Final remaining Year 2-3 curriculum questions  
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y2GS002', 'Geometry - Properties of Shapes', 'Identify and describe properties of 3-D shapes, including number of edges, vertices and faces', 'How many faces does a cube have?', 'Multiple Choice', '["6", "4", "8", "12"]', '6', 'Medium', ARRAY['3DShape_PropertyConfusion'], 'Student may confuse faces with vertices (8) or edges (12).', 'Year 2: 3D shape properties.', 'year 2-3'),
('Y3GS001', 'Geometry - Properties of Shapes', 'Draw 2-D shapes and make 3-D shapes using modelling materials', 'How many edges does a cube have?', 'Multiple Choice', '["12", "6", "8", "4"]', '12', 'Medium', ARRAY['3DShape_EdgeFaceConfusion'], 'Student may confuse edges with faces (6) or vertices (8).', 'Year 3: Properties of 3D shapes.', 'year 2-3'),
('Y3GS002', 'Geometry - Properties of Shapes', 'Recognise angles as a property of shape or a description of a turn', 'How many right angles are in a complete turn?', 'Multiple Choice', '["4", "2", "3", "1"]', '4', 'Medium', ARRAY['Angle_TurnConfusion'], 'Student may think of half turn (2 right angles) instead of full turn.', 'Year 3: Understanding angles and turns.', 'year 2-3'),
('Y3GS003', 'Geometry - Properties of Shapes', 'Identify horizontal and vertical lines and pairs of perpendicular and parallel lines', 'What do we call two lines that never meet?', 'Multiple Choice', '["Parallel", "Perpendicular", "Vertical", "Diagonal"]', 'Parallel', 'Medium', ARRAY['Lines_TermConfusion'], 'Student may confuse parallel with perpendicular (lines that meet at right angles).', 'Year 3: Understanding line relationships.', 'year 2-3'),
('Y2PD001', 'Geometry - Position and Direction', 'Use mathematical vocabulary to describe position, direction and movement', 'If you turn a quarter turn clockwise from facing North, which direction will you face?', 'Multiple Choice', '["East", "West", "South", "North"]', 'East', 'Hard', ARRAY['Direction_ClockwiseConfusion'], 'Student may turn anticlockwise instead, facing West.', 'Year 2: Understanding clockwise quarter turns.', 'year 2-3'),
('Y2PD002', 'Geometry - Position and Direction', 'Order and arrange combinations of mathematical objects in patterns and sequences', 'What comes next in this pattern: circle, square, circle, square, circle, __?', 'Multiple Choice', '["square", "circle", "triangle", "rectangle"]', 'square', 'Easy', NULL, NULL, 'Year 2: Basic pattern recognition.', 'year 2-3'),
('Y2ST001', 'Statistics', 'Interpret and construct simple pictograms, tally charts, block diagrams', 'In a pictogram where each picture represents 2 children, how many children do 3 pictures represent?', 'Multiple Choice', '["6", "3", "5", "2"]', '6', 'Medium', ARRAY['Pictogram_ScaleError'], 'Student may count pictures (3) instead of applying the scale.', 'Year 2: Understanding pictogram scales.', 'year 2-3'),
('Y3ST001', 'Statistics', 'Interpret and present data using bar charts, pictograms and tables', 'A bar chart shows 8 children like football and 5 like tennis. How many children were surveyed in total?', 'Multiple Choice', '["13", "3", "8", "40"]', '13', 'Easy', ARRAY['Statistics_DifferenceError'], 'Student may find difference (3) instead of total.', 'Year 3: Adding data values from bar charts.', 'year 2-3'),
('Y3ST002', 'Statistics', 'Solve one-step and two-step questions using information presented in scaled bar charts', 'In a bar chart where each square represents 5 people, a bar reaches 4 squares high. How many people does this represent?', 'Multiple Choice', '["20", "4", "9", "15"]', '20', 'Medium', ARRAY['BarChart_ScaleError'], 'Student may count squares (4) without applying scale, or add (4+5=9).', 'Year 3: Understanding scaled bar charts.', 'year 2-3');