-- Import Year 2-3 curriculum questions with proper PostgreSQL array syntax
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y2NPV001', 'Number - Number and Place Value', 'Count in steps of 2, 3, and 5 from 0, and in tens from any number', 'Count on in steps of 2 from 14. What is the next number: 14, 16, 18, __?', 'Multiple Choice', '["20", "19", "21", "22"]', '20', 'Easy', NULL, NULL, 'Year 2: Basic skip counting by 2s.', 'year 2-3'),
('Y2NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a two-digit number (tens, ones)', 'What is the value of the digit 4 in the number 47?', 'Multiple Choice', '["40", "4", "44", "400"]', '40', 'Medium', ARRAY['PlaceValue_DigitConfusion'], 'Student may confuse the digit itself (4) with its place value (40).', 'Year 2: Understanding tens place value.', 'year 2-3'),
('Y2NPV003', 'Number - Number and Place Value', 'Compare and order numbers from 0 up to 100; use <, > and = signs', 'Which sign makes this correct? 67 __ 76', 'Multiple Choice', '["<", ">", "=", "+"]', '<', 'Medium', ARRAY['Comparison_DirectionConfusion'], 'Student may confuse the direction of comparison signs.', 'Year 2: Understanding comparison symbols.', 'year 2-3'),
('Y3NPV001', 'Number - Number and Place Value', 'Count from 0 in multiples of 4, 8, 50 and 100', 'Count on in 50s from 200. What comes next: 200, 250, 300, __?', 'Multiple Choice', '["350", "400", "320", "500"]', '350', 'Easy', NULL, NULL, 'Year 3: Skip counting by 50s.', 'year 2-3'),
('Y3NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a three-digit number (hundreds, tens, ones)', 'What is the value of the digit 5 in the number 358?', 'Multiple Choice', '["50", "5", "500", "350"]', '50', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify wrong place value (5 for ones or 500 for hundreds).', 'Year 3: Understanding tens place in 3-digit numbers.', 'year 2-3'),
('Y3NPV003', 'Number - Number and Place Value', 'Compare and order numbers up to 1000', 'Order these numbers from smallest to largest: 567, 576, 657', 'Multiple Choice', '["567, 576, 657", "576, 567, 657", "657, 576, 567", "567, 657, 576"]', '567, 576, 657', 'Medium', ARRAY['Ordering_DigitConfusion'], 'Student may focus on individual digits rather than place value.', 'Year 3: Ordering 3-digit numbers.', 'year 2-3'),
('Y2ASM001', 'Number - Addition and Subtraction', 'Add and subtract numbers using concrete objects, pictorial representations, and mentally', 'What is 23 + 14?', 'Multiple Choice', '["37", "27", "47", "38"]', '37', 'Medium', ARRAY['Addition_PartialCalculation'], 'Student may only add the ones (3+4=7) and forget to add the tens.', 'Year 2: Basic two-digit addition.', 'year 2-3'),
('Y2ASM002', 'Number - Addition and Subtraction', 'Recall and use addition and subtraction facts to 20 fluently', 'What is 17 - 9?', 'Multiple Choice', '["8", "7", "6", "9"]', '8', 'Medium', ARRAY['Subtraction_CountingError'], 'Student may make a counting error when subtracting across 10.', 'Year 2: Fluency with facts crossing 10.', 'year 2-3'),
('Y3ASM001', 'Number - Addition and Subtraction', 'Add and subtract numbers mentally, including a three-digit number and ones', 'What is 345 + 7?', 'Multiple Choice', '["352", "342", "452", "315"]', '352', 'Easy', NULL, NULL, 'Year 3: Mental addition with 3-digit numbers.', 'year 2-3'),
('Y3ASM002', 'Number - Addition and Subtraction', 'Add and subtract numbers with up to three digits, using formal written methods', 'Calculate: 456 - 178', 'Multiple Choice', '["278", "378", "268", "288"]', '278', 'Hard', ARRAY['Subtraction_BorrowingError'], 'Student may make errors when borrowing across columns.', 'Year 3: Column subtraction with borrowing.', 'year 2-3');