-- Import the provided mock test questions
SELECT import_mock_test_questions('[
  {
    "question_id": "GL_NPV1_001",
    "question_text": "Which number has 7 in the millions place?",
    "question_type": "multiple_choice",
    "option_a": "1700000",
    "option_b": "7000000", 
    "option_c": "700000",
    "option_d": "17000000",
    "correct_answer": "B",
    "explanation": "7000000 has 7 in the millions place (7th position from right).",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Numbers to 10000000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv1,gl,numbers_to_10000000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV1_002",
    "question_text": "Write the largest 6-digit number using digits 3 7 1 9 2 5 exactly once.",
    "question_type": "multiple_choice",
    "option_a": "975321",
    "option_b": "321579",
    "option_c": "135792", 
    "option_d": "975123",
    "correct_answer": "A",
    "explanation": "Arrange digits in descending order: 975321 is the largest possible number.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Numbers to 10000000", 
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv1,cem,numbers_to_10000000",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV1_003",
    "question_text": "What is the place value of 6 in 4267891?",
    "question_type": "multiple_choice",
    "option_a": "Ten thousands",
    "option_b": "Hundred thousands",
    "option_c": "Thousands",
    "option_d": "Hundreds",
    "correct_answer": "A",
    "explanation": "Reading from right: 1(ones) 9(tens) 8(hundreds) 7(thousands) 6(ten thousands).",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Place value understanding",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv1,gl,place_value_understanding",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV1_004",
    "question_text": "Write ''four million two hundred thousand'' in figures.",
    "question_type": "multiple_choice",
    "option_a": "4200000",
    "option_b": "42000000",
    "option_c": "4020000",
    "option_d": "400200",
    "correct_answer": "A",
    "explanation": "Four million = 4000000 plus two hundred thousand = 200000 gives 4200000.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Standard and word form",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv1,gl,standard_and_word_form",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV1_005",
    "question_text": "A number in word form is ''three million forty-seven thousand six''. Write in figures and find the sum of all its digits.",
    "question_type": "multiple_choice",
    "option_a": "3047006 sum=20",
    "option_b": "3470006 sum=20",
    "option_c": "3047006 sum=23",
    "option_d": "3047600 sum=20",
    "correct_answer": "A",
    "explanation": "3047006: sum of digits = 3+0+4+7+0+0+6 = 20.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Standard and word form",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv1,cem,standard_and_word_form",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV2_006",
    "question_text": "Round 8749 to the nearest hundred.",
    "question_type": "multiple_choice",
    "option_a": "8700",
    "option_b": "8800",
    "option_c": "8750",
    "option_d": "9000",
    "correct_answer": "A",
    "explanation": "Look at tens digit (4). Since 4 < 5 round down to 8700.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 10",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv2,gl,rounding_to_nearest_10",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV2_007", 
    "question_text": "A factory produces 8749 items. Round to nearest 10 100 and 1000. Find the total of all rounded values.",
    "question_type": "multiple_choice",
    "option_a": "26450",
    "option_b": "26500",
    "option_c": "25450", 
    "option_d": "27450",
    "correct_answer": "A",
    "explanation": "8750 + 8700 + 9000 = 26450. Round each then add.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 10",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv2,cem,rounding_to_nearest_10",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV2_008",
    "question_text": "Round 45628 to the nearest 1000.",
    "question_type": "multiple_choice",
    "option_a": "45000",
    "option_b": "46000",
    "option_c": "45600",
    "option_d": "50000",
    "correct_answer": "B",
    "explanation": "Look at hundreds digit (6). Since 6 ≥ 5 round up to 46000.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 100",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv2,gl,rounding_to_nearest_100",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV2_009",
    "question_text": "Round 123456 to the nearest 10000.",
    "question_type": "multiple_choice",
    "option_a": "120000",
    "option_b": "130000",
    "option_c": "123000",
    "option_d": "100000",
    "correct_answer": "A",
    "explanation": "Look at thousands digit (3). Since 3 < 5 round down to 120000.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 1000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv2,gl,rounding_to_nearest_1000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV2_010",
    "question_text": "Round 876543 to the nearest 10000.",
    "question_type": "multiple_choice",
    "option_a": "870000",
    "option_b": "880000",
    "option_c": "876000",
    "option_d": "900000",
    "correct_answer": "B",
    "explanation": "Look at thousands digit (6). Since 6 ≥ 5 round up to 880000.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 10000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv2,gl,rounding_to_nearest_10000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV2_011",
    "question_text": "Round 876543 to nearest 100 and 10000. Find the difference between the rounded values.",
    "question_type": "multiple_choice",
    "option_a": "4400",
    "option_b": "4500",
    "option_c": "4000",
    "option_d": "5000",
    "correct_answer": "A",
    "explanation": "876500 - 880000 = -3500. But 880000 - 876500 = 3500. Check: difference is 3500.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Rounding to nearest 10000",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv2,cem,rounding_to_nearest_10000",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV3_012",
    "question_text": "Which symbol makes this correct: 34567 __ 34576?",
    "question_type": "multiple_choice",
    "option_a": ">",
    "option_b": "<",
    "option_c": "=",
    "option_d": "≠",
    "correct_answer": "B",
    "explanation": "Compare digits left to right: 3=3 4=4 5=5 6<7 so 34567 < 34576.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Using < > = symbols",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv3,gl,using_<_>_=_symbols",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV3_013",
    "question_text": "Order from smallest to largest: 234567 234576 234657 234675. Explain your method.",
    "question_type": "multiple_choice",
    "option_a": "234567, 234576, 234657, 234675",
    "option_b": "234675, 234657, 234576, 234567",
    "option_c": "234567, 234657, 234576, 234675",
    "option_d": "234576, 234567, 234675, 234657",
    "correct_answer": "A",
    "explanation": "Compare digit by digit from left. All start 234 so compare next: 5<5<6<6 then 6<7<5<7.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Using < > = symbols",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv3,cem,using_<_>_=_symbols",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV3_014",
    "question_text": "Which is the largest number?",
    "question_type": "multiple_choice",
    "option_a": "567890",
    "option_b": "567809",
    "option_c": "567980",
    "option_d": "567098",
    "correct_answer": "C",
    "explanation": "Compare: 567890 vs 567809 vs 567980 vs 567098. Third digit: 7>7>7>7 fourth: 8>8>9>0 so 567980.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Ordering large numbers",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv3,gl,ordering_large_numbers",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV3_015",
    "question_text": "On a number line which number is halfway between 2000 and 3000?",
    "question_type": "multiple_choice",
    "option_a": "2400",
    "option_b": "2500",
    "option_c": "2600",
    "option_d": "2250",
    "correct_answer": "B",
    "explanation": "Halfway = (2000 + 3000) ÷ 2 = 5000 ÷ 2 = 2500.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Number lines",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv3,gl,number_lines",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV4_016",
    "question_text": "What is XL in Hindu-Arabic numerals?",
    "question_type": "multiple_choice",
    "option_a": "40",
    "option_b": "50",
    "option_c": "60",
    "option_d": "90",
    "correct_answer": "A",
    "explanation": "X = 10 and L = 50. XL means 10 before 50 = 50 - 10 = 40.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Roman numerals to 100",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv4,gl,roman_numerals_to_100",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV4_017",
    "question_text": "Write 1994 in Roman numerals and explain why this uses subtraction principle twice.",
    "question_type": "multiple_choice",
    "option_a": "MCMXCIV - uses CM and IV",
    "option_b": "MCDXCIV - uses CD and IV",
    "option_c": "MCMLXXXXIV - no subtraction",
    "option_d": "MMDXCIV - incorrect",
    "correct_answer": "A",
    "explanation": "1994 = 1000 + 900 + 90 + 4 = M + CM + XC + IV. CM (900) and XC (90) both use subtraction.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Roman numerals to 100",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv4,cem,roman_numerals_to_100",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV4_018",
    "question_text": "What is CDXL in Hindu-Arabic numerals?",
    "question_type": "multiple_choice",
    "option_a": "440",
    "option_b": "540",
    "option_c": "460",
    "option_d": "640",
    "correct_answer": "A",
    "explanation": "C = 100 D = 500 X = 10 L = 50. CD = 400 XL = 40. Total = 440.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Roman numerals to 1000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv4,gl,roman_numerals_to_1000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV4_019",
    "question_text": "Convert 247 to Roman numerals.",
    "question_type": "multiple_choice",
    "option_a": "CCXLVII",
    "option_b": "CCXXXXVII",
    "option_c": "CCXLVII",
    "option_d": "CCXLVII",
    "correct_answer": "A",
    "explanation": "247 = 200 + 40 + 7 = CC + XL + VII = CCXLVII.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Converting between systems",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv4,gl,converting_between_systems",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV5_020",
    "question_text": "Which shows the correct understanding of negative numbers?",
    "question_type": "multiple_choice",
    "option_a": "-5 is warmer than -10",
    "option_b": "-10 is warmer than -5",
    "option_c": "-5 and -10 are the same",
    "option_d": "Temperature cannot be negative",
    "correct_answer": "A",
    "explanation": "-5°C is warmer than -10°C. -5 is greater than -10 on the number line.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Understanding negative numbers",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv5,gl,understanding_negative_numbers",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV5_021",
    "question_text": "The temperature at 6am was -8°C. By noon it had risen 15°C. What was the noon temperature?",
    "question_type": "multiple_choice",
    "option_a": "7°C",
    "option_b": "23°C",
    "option_c": "-23°C",
    "option_d": "15°C",
    "correct_answer": "A",
    "explanation": "-8 + 15 = 7. Start at -8 on number line move 15 places right to reach 7.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Understanding negative numbers",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv5,cem,understanding_negative_numbers",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV5_022",
    "question_text": "Order from smallest to largest: -3 -7 -1 -9",
    "question_type": "multiple_choice",
    "option_a": "-9, -7, -3, -1",
    "option_b": "-1, -3, -7, -9",
    "option_c": "-7, -9, -1, -3",
    "option_d": "-3, -1, -7, -9",
    "correct_answer": "A",
    "explanation": "On number line: -9 is furthest left (smallest) then -7 -3 -1 (largest).",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Ordering negative numbers",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv5,gl,ordering_negative_numbers",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV5_023",
    "question_text": "The temperature dropped from 3°C to -5°C. What was the change?",
    "question_type": "multiple_choice",
    "option_a": "8°C decrease",
    "option_b": "2°C decrease",
    "option_c": "8°C increase",
    "option_d": "2°C increase",
    "correct_answer": "A",
    "explanation": "From 3 to -5: count down 3 to 0 (3 degrees) then 0 to -5 (5 degrees) = 8°C decrease.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Temperature problems",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv5,gl,temperature_problems",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV5_024",
    "question_text": "Which point is 4 units left of 1 on the number line?",
    "question_type": "multiple_choice",
    "option_a": "-3",
    "option_b": "-4",
    "option_c": "-2",
    "option_d": "3",
    "correct_answer": "A",
    "explanation": "From 1 move 4 units left: 1 → 0 → -1 → -2 → -3.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Number line with negatives",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv5,gl,number_line_with_negatives",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV5_025",
    "question_text": "On a number line the distance between -7 and 3 is 10 units. Explain why and find another pair with same distance.",
    "question_type": "multiple_choice",
    "option_a": "10 units, -2 and 8",
    "option_b": "8 units, -1 and 7",
    "option_c": "10 units, 0 and 10",
    "option_d": "6 units, -4 and 2",
    "correct_answer": "A",
    "explanation": "Distance = |3 - (-7)| = |3 + 7| = 10. Any two numbers that differ by 10 work: -2 and 8.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Number line with negatives",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv5,cem,number_line_with_negatives",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV6_026",
    "question_text": "Which number is prime?",
    "question_type": "multiple_choice",
    "option_a": "21",
    "option_b": "27",
    "option_c": "29",
    "option_d": "33",
    "correct_answer": "C",
    "explanation": "29 is only divisible by 1 and 29. Others: 21=3×7 27=3×9 33=3×11.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Identifying prime numbers",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv6,gl,identifying_prime_numbers",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV6_027",
    "question_text": "List all prime numbers between 20 and 40. Explain why 39 is not prime.",
    "question_type": "multiple_choice",
    "option_a": "23, 29, 31, 37 (39 = 3 × 13)",
    "option_b": "21, 23, 29, 31, 37",
    "option_c": "23, 27, 29, 31, 37",
    "option_d": "23, 29, 31, 37, 39",
    "correct_answer": "A",
    "explanation": "Primes: 23 29 31 37. 39 = 3 × 13 so has factors other than 1 and itself.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Identifying prime numbers",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv6,cem,identifying_prime_numbers",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV6_028",
    "question_text": "Which are factors of 24?",
    "question_type": "multiple_choice",
    "option_a": "1, 2, 3, 4, 6, 8, 12, 24",
    "option_b": "1, 2, 4, 6, 12, 24",
    "option_c": "2, 3, 4, 6, 8, 12",
    "option_d": "1, 3, 6, 8, 12, 24",
    "correct_answer": "A",
    "explanation": "All numbers that divide 24 exactly: 24÷1=24 24÷2=12 24÷3=8 24÷4=6 24÷6=4 24÷8=3 24÷12=2 24÷24=1.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Finding factors",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv6,gl,finding_factors",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV6_029",
    "question_text": "Which are the first 5 multiples of 7?",
    "question_type": "multiple_choice",
    "option_a": "7, 14, 21, 28, 35",
    "option_b": "0, 7, 14, 21, 28",
    "option_c": "1, 7, 14, 21, 28",
    "option_d": "7, 14, 21, 28, 42",
    "correct_answer": "A",
    "explanation": "Multiples of 7: 7×1=7 7×2=14 7×3=21 7×4=28 7×5=35.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Finding multiples",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv6,gl,finding_multiples",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV6_030",
    "question_text": "What is the highest common factor of 18 and 24?",
    "question_type": "multiple_choice",
    "option_a": "6",
    "option_b": "12",
    "option_c": "3",
    "option_d": "9",
    "correct_answer": "A",
    "explanation": "Factors of 18: 1 2 3 6 9 18. Factors of 24: 1 2 3 4 6 8 12 24. Common: 1 2 3 6. Highest: 6.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Common factors and multiples",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv6,gl,common_factors_and_multiples",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV6_031",
    "question_text": "Find HCF and LCM of 12 and 18. Verify that HCF × LCM = 12 × 18.",
    "question_type": "multiple_choice",
    "option_a": "HCF=6, LCM=36, 6×36=216=12×18",
    "option_b": "HCF=3, LCM=72",
    "option_c": "HCF=6, LCM=72",
    "option_d": "HCF=9, LCM=36",
    "correct_answer": "A",
    "explanation": "HCF(12,18)=6 LCM(12,18)=36. Check: 6×36=216 and 12×18=216 ✓",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Common factors and multiples",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv6,cem,common_factors_and_multiples",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV7_032",
    "question_text": "What is 11²?",
    "question_type": "multiple_choice",
    "option_a": "121",
    "option_b": "111",
    "option_c": "101",
    "option_d": "131",
    "correct_answer": "A",
    "explanation": "11² = 11 × 11 = 121.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Square numbers to 144",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv7,gl,square_numbers_to_144",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV7_033",
    "question_text": "Which square numbers are between 50 and 100? Find the difference between the largest and smallest.",
    "question_type": "multiple_choice",
    "option_a": "64, 81; difference = 17",
    "option_b": "49, 64, 81, 100; difference = 51",
    "option_c": "64, 81, 100; difference = 36",
    "option_d": "36, 49, 64, 81; difference = 45",
    "correct_answer": "A",
    "explanation": "8²=64 9²=81 are between 50 and 100. Difference: 81-64=17.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Square numbers to 144",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv7,cem,square_numbers_to_144",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV7_034",
    "question_text": "What is 8³?",
    "question_type": "multiple_choice",
    "option_a": "512",
    "option_b": "64",
    "option_c": "24",
    "option_d": "888",
    "correct_answer": "A",
    "explanation": "8³ = 8 × 8 × 8 = 64 × 8 = 512.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Cube numbers to 1000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv7,gl,cube_numbers_to_1000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV7_035",
    "question_text": "What pattern do you see in square numbers: 1 4 9 16 25?",
    "question_type": "multiple_choice",
    "option_a": "Add 3 then 5 then 7 then 9",
    "option_b": "Add 3 each time",
    "option_c": "Multiply by 2 each time",
    "option_d": "Add consecutive numbers",
    "correct_answer": "A",
    "explanation": "Differences: 4-1=3 9-4=5 16-9=7 25-16=9. Pattern: add odd numbers.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Recognizing patterns",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv7,gl,recognizing_patterns",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV8_036",
    "question_text": "Draw the factor tree for 24.",
    "question_type": "multiple_choice",
    "option_a": "24 = 2³ × 3",
    "option_b": "24 = 4 × 6",
    "option_c": "24 = 8 × 3",
    "option_d": "24 = 12 × 2",
    "correct_answer": "A",
    "explanation": "24 = 2×12 = 2×2×6 = 2×2×2×3 = 2³×3.",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Factor trees",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv8,gl,factor_trees",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV8_037",
    "question_text": "Find prime factorization of 60 and 84. Use this to find their HCF.",
    "question_type": "multiple_choice",
    "option_a": "60=2²×3×5, 84=2²×3×7, HCF=12",
    "option_b": "60=2×30, 84=4×21, HCF=6",
    "option_c": "60=4×15, 84=12×7, HCF=4",
    "option_d": "60=6×10, 84=6×14, HCF=6",
    "correct_answer": "A",
    "explanation": "60=2²×3×5 84=2²×3×7. HCF=2²×3=12 (common factors).",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "Factor trees",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv8,cem,factor_trees",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV8_038",
    "question_text": "What is 36 in prime factor form?",
    "question_type": "multiple_choice",
    "option_a": "2² × 3²",
    "option_b": "6²",
    "option_c": "4 × 9",
    "option_d": "2 × 3⁴",
    "correct_answer": "A",
    "explanation": "36 = 6×6 = (2×3)×(2×3) = 2²×3².",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "Prime factor form",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv8,gl,prime_factor_form",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV8_039",
    "question_text": "Using prime factors find HCF of 18 and 30.",
    "question_type": "multiple_choice",
    "option_a": "6",
    "option_b": "9",
    "option_c": "3",
    "option_d": "15",
    "correct_answer": "A",
    "explanation": "18=2×3² 30=2×3×5. HCF=2×3=6 (common factors).",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "HCF using prime factors",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv8,gl,hcf_using_prime_factors",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_NPV8_040",
    "question_text": "Using prime factors find LCM of 12 and 18.",
    "question_type": "multiple_choice",
    "option_a": "36",
    "option_b": "6",
    "option_c": "72",
    "option_d": "24",
    "correct_answer": "A",
    "explanation": "12=2²×3 18=2×3². LCM=2²×3²=4×9=36 (highest powers).",
    "difficulty": "easy",
    "topic": "Number and Place Value",
    "subtopic": "LCM using prime factors",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "npv8,gl,lcm_using_prime_factors",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_NPV8_041",
    "question_text": "Find LCM of 24 36 and 40 using prime factorization. Check your answer.",
    "question_type": "multiple_choice",
    "option_a": "360",
    "option_b": "120",
    "option_c": "720",
    "option_d": "180",
    "correct_answer": "A",
    "explanation": "24=2³×3 36=2²×3² 40=2³×5. LCM=2³×3²×5=8×9×5=360.",
    "difficulty": "medium",
    "topic": "Number and Place Value",
    "subtopic": "LCM using prime factors",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "npv8,cem,lcm_using_prime_factors",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO1_042",
    "question_text": "Calculate: 450 + 70",
    "question_type": "multiple_choice",
    "option_a": "520",
    "option_b": "530",
    "option_c": "510",
    "option_d": "540",
    "correct_answer": "A",
    "explanation": "450 + 70 = 520. Add directly or use 450 + 50 + 20.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "Adding multiples of 10 100 1000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao1,gl,adding_multiples_of_10_100_1000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_AO1_043",
    "question_text": "Use mental math to find 397 + 284. Show your compensation strategy.",
    "question_type": "multiple_choice",
    "option_a": "681",
    "option_b": "671",
    "option_c": "691",
    "option_d": "680",
    "correct_answer": "A",
    "explanation": "397 + 284 = 400 + 281 = 681. Compensate by adding 3 to 397 and subtracting 3 from 284.",
    "difficulty": "medium",
    "topic": "Arithmetic Operations",
    "subtopic": "Adding multiples of 10 100 1000",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "ao1,cem,adding_multiples_of_10_100_1000",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO1_044",
    "question_text": "Calculate: 560 - 80",
    "question_type": "multiple_choice",
    "option_a": "480",
    "option_b": "580",
    "option_c": "470",
    "option_d": "490",
    "correct_answer": "A",
    "explanation": "560 - 80 = 480. Subtract directly.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "Subtracting multiples of 10 100 1000",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao1,gl,subtracting_multiples_of_10_100_1000",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO1_045",
    "question_text": "Double 34 then add 1.",
    "question_type": "multiple_choice",
    "option_a": "69",
    "option_b": "68",
    "option_c": "67",
    "option_d": "70",
    "correct_answer": "A",
    "explanation": "Double 34: 34 × 2 = 68. Then add 1: 68 + 1 = 69.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "Near doubles",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao1,gl,near_doubles",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO1_046",
    "question_text": "Calculate 47 + 49 using doubles.",
    "question_type": "multiple_choice",
    "option_a": "96",
    "option_b": "94",
    "option_c": "98",
    "option_d": "92",
    "correct_answer": "A",
    "explanation": "47 + 49 = 48 + 48 = 96. Use double 48 (halfway between 47 and 49).",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "Compensation strategies",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao1,gl,compensation_strategies",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_AO1_047",
    "question_text": "Calculate 298 + 147 using compensation. Explain your strategy.",
    "question_type": "multiple_choice",
    "option_a": "445",
    "option_b": "435",
    "option_c": "455",
    "option_d": "440",
    "correct_answer": "A",
    "explanation": "298 + 147 = 300 + 145 = 445. Add 2 to 298 (→300) subtract 2 from 147 (→145).",
    "difficulty": "medium",
    "topic": "Arithmetic Operations",
    "subtopic": "Compensation strategies",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "ao1,cem,compensation_strategies",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO2_048",
    "question_text": "Add: 234 + 567",
    "question_type": "multiple_choice",
    "option_a": "801",
    "option_b": "791",
    "option_c": "811",
    "option_d": "701",
    "correct_answer": "A",
    "explanation": "234 + 567: 4+7=11 (carry 1) 3+6+1=10 (carry 1) 2+5+1=8. Answer: 801.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "3-digit addition",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao2,gl,3-digit_addition",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "CEM_AO2_049",
    "question_text": "Add 1234 + 5678 + 9012. Check your answer by estimating.",
    "question_type": "multiple_choice",
    "option_a": "15924",
    "option_b": "15934",
    "option_c": "16024",
    "option_d": "15824",
    "correct_answer": "A",
    "explanation": "1234+5678=6912 6912+9012=15924. Estimate: 1000+6000+9000=16000 ✓",
    "difficulty": "medium",
    "topic": "Arithmetic Operations",
    "subtopic": "3-digit addition",
    "marks": 3,
    "time_seconds": 150,
    "visual_aid_url": "",
    "tags": "ao2,cem,3-digit_addition",
    "exam_board": "CEM",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO2_050",
    "question_text": "Add: 3456 + 7890",
    "question_type": "multiple_choice",
    "option_a": "11346",
    "option_b": "11246",
    "option_c": "11356",
    "option_d": "10346",
    "correct_answer": "A",
    "explanation": "3456 + 7890: 6+0=6 5+9=14 (carry 1) 4+8+1=13 (carry 1) 3+7+1=11. Answer: 11346.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "4-digit addition",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao2,gl,4-digit_addition",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO2_051",
    "question_text": "Add: 12345 + 67890",
    "question_type": "multiple_choice",
    "option_a": "80235",
    "option_b": "80135",
    "option_c": "79235",
    "option_d": "81235",
    "correct_answer": "A",
    "explanation": "Add column by column with carrying: 5+0=5 4+9=13 3+8+1=12 2+7+1=10 1+6+1=8. Answer: 80235.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "5+ digit addition",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao2,gl,5+_digit_addition",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  },
  {
    "question_id": "GL_AO2_052",
    "question_text": "Add: 23.4 + 56.7",
    "question_type": "multiple_choice",
    "option_a": "80.1",
    "option_b": "79.1",
    "option_c": "81.1",
    "option_d": "70.1",
    "correct_answer": "A",
    "explanation": "Line up decimal points: 23.4 + 56.7 = 80.1.",
    "difficulty": "easy",
    "topic": "Arithmetic Operations",
    "subtopic": "Decimal addition",
    "marks": 2,
    "time_seconds": 90,
    "visual_aid_url": "",
    "tags": "ao2,gl,decimal_addition",
    "exam_board": "GL",
    "year_level": 7,
    "is_active": true
  }
]'::jsonb);