-- Import missing Year 4-5 curriculum questions 
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y5ASM001', 'Number - Addition and Subtraction', 'Add and subtract whole numbers with more than 4 digits', 'Calculate: 45,678 - 17,892', 'Multiple Choice', '["27,786", "28,786", "27,886", "63,570"]', '27,786', 'Medium', ARRAY['Subtraction_BorrowingError'], 'Student may make errors when borrowing across multiple columns.', 'Year 5: 5-digit subtraction with borrowing.', 'year 4-5'),
('Y5ASM002', 'Number - Addition and Subtraction', 'Solve addition and subtraction multi-step problems in contexts', 'A company had £45,600. They received £12,350 in sales, paid £8,900 in wages, and spent £5,750 on supplies. How much money do they have now?', 'Multiple Choice', '["£43,300", "£72,600", "£38,300", "£42,300"]', '£43,300', 'Very Hard', ARRAY['MultiStep_OrderOfOperations'], 'Student may add all positive amounts and subtract negatives incorrectly.', 'Year 5: Complex multi-step problem with money.', 'year 4-5'),
('Y5MD001', 'Number - Multiplication and Division', 'Multiply numbers up to 4 digits by a one- or two-digit number using formal written method', 'Calculate: 1,234 × 25', 'Multiple Choice', '["30,850", "28,850", "31,850", "25,850"]', '30,850', 'Very Hard', ARRAY['LongMultiplication_PartialProductError'], 'Student may make errors when adding partial products in long multiplication.', 'Year 5: Long multiplication with 4-digit by 2-digit numbers.', 'year 4-5'),
('Y5MD002', 'Number - Multiplication and Division', 'Divide numbers up to 4 digits by a one-digit number and interpret remainders', 'Calculate: 725 ÷ 6', 'Multiple Choice', '["120 remainder 5", "121 remainder 1", "120 remainder 3", "125"]', '120 remainder 5', 'Hard', ARRAY['Division_RemainderError'], 'Student may calculate remainder incorrectly or forget to include it.', 'Year 5: Division with remainders.', 'year 4-5'),
('Y5MD003', 'Number - Multiplication and Division', 'Identify multiples and factors, including finding all factor pairs', 'Which of these is NOT a factor of 24?', 'Multiple Choice', '["5", "6", "8", "3"]', '5', 'Medium', ARRAY['Factors_NonFactorConfusion'], 'Student may not check if number divides evenly into 24.', 'Year 5: Identifying factors of numbers.', 'year 4-5'),
('Y5MD004', 'Number - Multiplication and Division', 'Know and use the vocabulary of prime numbers, prime factors and composite numbers', 'Which of these is a prime number?', 'Multiple Choice', '["17", "15", "21", "27"]', '17', 'Medium', ARRAY['PrimeNumbers_OddNumberConfusion'], 'Student may think all odd numbers are prime.', 'Year 5: Identifying prime numbers.', 'year 4-5'),
('Y5FR001', 'Number - Fractions (including decimals and percentages)', 'Compare and order fractions whose denominators are multiples of the same number', 'Which is larger: 2/3 or 5/6?', 'Multiple Choice', '["5/6", "2/3", "They are equal", "Cannot tell"]', '5/6', 'Hard', ARRAY['FractionComparison_CommonDenominator'], 'Student may not find common denominator to compare (2/3 = 4/6).', 'Year 5: Comparing fractions with related denominators.', 'year 4-5'),
('Y5FR002', 'Number - Fractions (including decimals and percentages)', 'Recognise mixed numbers and improper fractions and convert from one form to the other', 'Convert 7/4 to a mixed number.', 'Multiple Choice', '["1 3/4", "3 1/4", "1 4/7", "7 1/4"]', '1 3/4', 'Medium', ARRAY['MixedNumber_ConversionError'], 'Student may invert the fraction or calculate whole number incorrectly.', 'Year 5: Converting improper fractions to mixed numbers.', 'year 4-5'),
('Y5FR003', 'Number - Fractions (including decimals and percentages)', 'Add and subtract fractions with denominators that are multiples of the same number', 'Calculate: 1/2 + 1/4', 'Multiple Choice', '["3/4", "2/6", "1/6", "2/4"]', '3/4', 'Medium', ARRAY['Fractions_UnlikeAddition'], 'Student may add numerators and denominators directly (1+1=2, 2+4=6).', 'Year 5: Adding fractions with different but related denominators.', 'year 4-5'),
('Y5FR004', 'Number - Fractions (including decimals and percentages)', 'Multiply proper fractions and mixed numbers by whole numbers', 'Calculate: 3/4 × 2', 'Multiple Choice', '["1 1/2", "3/8", "6/4", "3/2"]', '1 1/2', 'Hard', ARRAY['FractionMultiplication_WholeNumber'], 'Student may divide instead of multiply or not convert to mixed number.', 'Year 5: Multiplying fractions by whole numbers.', 'year 4-5');