-- Continue importing remaining Year 5 curriculum questions
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y5FR005', 'Number - Fractions (including decimals and percentages)', 'Recognise the per cent symbol (%) and understand that per cent relates to ''number of parts per hundred''', 'What is 25% as a fraction?', 'Multiple Choice', '["1/4", "1/25", "25/10", "2/5"]', '1/4', 'Medium', ARRAY['Percentage_FractionConversion'], 'Student may write 1/25 thinking percent means ''out of'' the number.', 'Year 5: Converting percentages to fractions.', 'year 4-5'),
('Y5FR006', 'Number - Fractions (including decimals and percentages)', 'Solve problems which require knowing percentage and decimal equivalents', 'What is 20% of 60?', 'Multiple Choice', '["12", "20", "40", "3"]', '12', 'Hard', ARRAY['Percentage_CalculationError'], 'Student may divide 60 by 20 (=3) or subtract 20 from 60 (=40).', 'Year 5: Finding percentages of amounts.', 'year 4-5'),
('Y5ME001', 'Measurement', 'Convert between different units of metric measure', 'Convert 2.5kg to grams.', 'Multiple Choice', '["2,500g", "250g", "25g", "25,000g"]', '2,500g', 'Medium', ARRAY['MetricConversion_DecimalError'], 'Student may misplace decimal when converting (250g).', 'Year 5: Converting kilograms to grams with decimals.', 'year 4-5'),
('Y5ME002', 'Measurement', 'Calculate and compare the area of rectangles using standard units', 'A rectangle has length 12cm and width 7cm. What is its area?', 'Multiple Choice', '["84 cm²", "19 cm²", "38 cm²", "84 cm"]', '84 cm²', 'Medium', ARRAY['Area_PerimeterConfusion'], 'Student may calculate perimeter (38cm) instead of area, or add dimensions.', 'Year 5: Calculating area of rectangles.', 'year 4-5'),
('Y5ME003', 'Measurement', 'Estimate volume and capacity', 'A cube has sides of 3cm. What is its volume?', 'Multiple Choice', '["27 cm³", "9 cm³", "18 cm³", "12 cm³"]', '27 cm³', 'Hard', ARRAY['Volume_AreaConfusion'], 'Student may calculate area of one face (9 cm²) or perimeter instead.', 'Year 5: Calculating volume of cubes.', 'year 4-5'),
('Y4GS001', 'Geometry - Properties of Shapes', 'Compare and classify geometric shapes, including quadrilaterals and triangles', 'Which type of triangle has all sides of different lengths?', 'Multiple Choice', '["Scalene", "Isosceles", "Equilateral", "Right-angled"]', 'Scalene', 'Medium', ARRAY['Triangle_TypeConfusion'], 'Student may confuse triangle classifications.', 'Year 4: Identifying triangle types by side lengths.', 'year 4-5'),
('Y5GS001', 'Geometry - Properties of Shapes', 'Identify 3-D shapes from 2-D representations', 'Which 3-D shape has 6 square faces?', 'Multiple Choice', '["Cube", "Cuboid", "Pyramid", "Sphere"]', 'Cube', 'Easy', ARRAY['3DShape_PropertyError'], 'Student may confuse cube with cuboid (rectangular faces).', 'Year 5: Identifying 3D shapes by properties.', 'year 4-5'),
('Y5GS002', 'Geometry - Properties of Shapes', 'Know angles are measured in degrees; estimate and compare acute, obtuse and reflex angles', 'What is the size of a right angle in degrees?', 'Multiple Choice', '["90°", "180°", "45°", "360°"]', '90°', 'Easy', NULL, NULL, 'Year 5: Basic angle measurements.', 'year 4-5'),
('Y5GS003', 'Geometry - Properties of Shapes', 'Identify angles at a point and one whole turn (total 360°)', 'Three angles at a point measure 120°, 80°, and one unknown angle. What is the unknown angle?', 'Multiple Choice', '["160°", "200°", "140°", "180°"]', '160°', 'Hard', ARRAY['AngleSum_CalculationError'], 'Student may add given angles incorrectly or subtract from wrong total.', 'Year 5: Finding missing angles at a point.', 'year 4-5'),
('Y5GS004', 'Geometry - Properties of Shapes', 'Distinguish between regular and irregular polygons based on reasoning about equal sides and angles', 'Which of these is a regular polygon?', 'Multiple Choice', '["A square", "A rectangle", "A rhombus", "An isosceles triangle"]', 'A square', 'Medium', ARRAY['RegularPolygon_Definition'], 'Student may think any shape with equal sides is regular (rhombus).', 'Year 5: Understanding regular polygons need equal sides AND angles.', 'year 4-5');