-- Restore large batch of additional Year 4 curriculum questions

INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, year_level, age_group
) VALUES 
('Y4NPV005', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count on in 6s from 42. What are the next two numbers?', 'Multiple Choice', '["48, 54", "47, 52", "48, 55", "49, 56"]', '48, 54', 'Easy', NULL, NULL, 'Year 4: Skip counting by 6s.', 4, 'year 4-5'),
('Y4NPV006', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'A sequence counts up in 7s. Fill the blank: 21, 28, __, 42.', 'Multiple Choice', '["35", "34", "36", "30"]', '35', 'Easy', NULL, NULL, 'Year 4: Finding a missing number in a sequence of 7s.', 4, 'year 4-5'),
('Y4NPV007', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count back in 9s from 90. What is the next number?', 'Multiple Choice', '["81", "99", "80", "79"]', '81', 'Easy', NULL, NULL, 'Year 4: Counting backwards in multiples of 9.', 4, 'year 4-5'),
('Y4NPV008', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'What is 1000 more than 4500?', 'Multiple Choice', '["5500", "4600", "3500", "4501"]', '5500', 'Easy', NULL, NULL, 'Year 4: Skip counting by 1000s.', 4, 'year 4-5'),
('Y4NPV009', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count back in 25s from 75. What are the next two numbers?', 'Multiple Choice', '["50, 25", "100, 125", "50, 0", "65, 55"]', '50, 25', 'Easy', NULL, NULL, 'Year 4: Counting backwards in multiples of 25.', 4, 'year 4-5'),
('Y4NPV010', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Which number is NOT a multiple of 6?', 'Multiple Choice', '["32", "18", "24", "60"]', '32', 'Easy', NULL, NULL, 'Year 4: Identifying multiples of 6.', 4, 'year 4-5'),
('Y4NPV011', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Which number is a multiple of 9?', 'Multiple Choice', '["27", "19", "35", "42"]', '27', 'Easy', NULL, NULL, 'Year 4: Identifying multiples of 9.', 4, 'year 4-5'),
('Y4NPV012', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count on in 1000s from 2345. What comes next?', 'Multiple Choice', '["3345", "2445", "1345", "2355"]', '3345', 'Easy', NULL, NULL, 'Year 4: Adding 1000 to a 4-digit number.', 4, 'year 4-5'),
('Y4NPV013', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count back in 7s from 49. Which number do you say?', 'Multiple Choice', '["35", "42", "56", "48"]', '35', 'Easy', NULL, 'Students might count up instead of down, or count by the wrong multiple.', 'Year 4: Skip counting backwards by 7s.', 4, 'year 4-5'),
('Y4NPV014', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Fill the blank in this sequence of 25s: 225, 250, __, 300.', 'Multiple Choice', '["275", "265", "280", "220"]', '275', 'Easy', NULL, NULL, 'Year 4: Finding a missing number in a sequence of 25s.', 4, 'year 4-5'),
('Y4NPV015', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'In the number 8,052, what is the value of the digit 5?', 'Multiple Choice', '["50", "5", "500", "5000"]', '50', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify the digit''s face value (5) instead of its place value (50 for tens).', 'Year 4: Understanding the tens place in 4-digit numbers, especially with a zero placeholder.', 4, 'year 4-5'),
('Y4NPV016', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What number is made up of 6 thousands, 0 hundreds, 2 tens, and 9 ones?', 'Multiple Choice', '["6,029", "6,290", "6,092", "6,209"]', '6,029', 'Medium', ARRAY['PlaceValue_ConstructionError'], 'Student may misplace the digits, especially confusing the tens and ones place or ignoring the zero placeholder.', 'Year 4: Constructing a 4-digit number from its component place values.', 4, 'year 4-5'),
('Y4NPV017', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'How many hundreds are there in the number 4,913?', 'Multiple Choice', '["9", "900", "49", "1"]', '9', 'Medium', ARRAY['PlaceValue_ValueVsDigit'], 'Student may state the value (900) instead of the digit in that place.', 'Year 4: Identifying the digit in the hundreds place.', 4, 'year 4-5'),
('Y4NPV018', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What is the value of the thousands digit in 5,678?', 'Multiple Choice', '["5,000", "5", "500", "1,000"]', '5,000', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify the digit itself (5) instead of its full value (5,000).', 'Year 4: Understanding the thousands place in 4-digit numbers.', 4, 'year 4-5'),
('Y4NPV019', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'Which digit is in the ones place in the number 2,341?', 'Multiple Choice', '["1", "2", "4", "10"]', '1', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify the first digit (2) instead of the last digit for the ones place.', 'Year 4: Identifying the digit in the ones place.', 4, 'year 4-5'),
('Y4NPV020', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'The number 1,111 is made of four ''1''s. Which ''1'' has the smallest value?', 'Multiple Choice', '["The one on the far right", "The one on the far left", "They all have the same value", "The second one from the left"]', 'The one on the far right', 'Medium', ARRAY['PlaceValue_Concept'], 'Student may think all digits ''1'' are equal, ignoring place value.', 'Year 4: Conceptual understanding of place value hierarchy.', 4, 'year 4-5'),
('Y4NPV021', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What does the digit 3 represent in the number 9,832?', 'Multiple Choice', '["3 tens", "3 hundreds", "3 ones", "3 thousands"]', '3 tens', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may misidentify the position, for example, calling it the hundreds place.', 'Year 4: Describing place value using words.', 4, 'year 4-5'),
('Y4NPV022', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'In 7,204, the digit 0 is a placeholder for which place value?', 'Multiple Choice', '["Tens", "Hundreds", "Ones", "Thousands"]', 'Tens', 'Medium', ARRAY['PlaceValue_ZeroPlaceholder'], 'Student may confuse the place value of the zero, often with the hundreds place next to it.', 'Year 4: Understanding the role of zero as a placeholder.', 4, 'year 4-5'),
('Y4NPV023', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'If you add 100 to 2,950, which digit changes?', 'Multiple Choice', '["The hundreds and thousands digits", "The tens digit", "The ones digit", "The hundreds digit only"]', 'The hundreds and thousands digits', 'Medium', ARRAY['PlaceValue_BoundaryCrossing'], 'Student may not realize that adding 100 to 900 results in 1000, causing a change in the thousands place as well.', 'Year 4: Applying place value knowledge to addition across a boundary (900 to 1000).', 4, 'year 4-5'),
('Y4NPV024', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What is 10 less than 4,000?', 'Multiple Choice', '["3,990", "3,900", "4,010", "3,999"]', '3,990', 'Medium', ARRAY['PlaceValue_BoundaryCrossing'], 'Student may struggle to subtract across multiple place value boundaries (from thousands).', 'Year 4: Applying place value knowledge to subtraction across boundaries.', 4, 'year 4-5')

ON CONFLICT (question_id) DO NOTHING;