-- Restore all curriculum questions from migration history

-- First restore Year 2-3 questions
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y2NPV001', 'Number - Number and Place Value', 'Count in steps of 2, 3, and 5 from 0, and in tens from any number', 'Count on in steps of 2 from 14. What is the next number: 14, 16, 18, __?', 'Multiple Choice', '["20", "19", "21", "22"]', '20', 'Easy', NULL, NULL, 'Year 2: Basic skip counting by 2s.', 'year 2-3'),
('Y2NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a two-digit number (tens, ones)', 'What is the value of the digit 4 in the number 47?', 'Multiple Choice', '["40", "4", "44", "400"]', '40', 'Medium', ARRAY['PlaceValue_DigitConfusion'], 'Student may confuse the digit itself (4) with its place value (40).', 'Year 2: Understanding tens place value.', 'year 2-3'),
('Y2NPV003', 'Number - Number and Place Value', 'Compare and order numbers from 0 up to 100; use <, > and = signs', 'Which sign makes this correct? 67 __ 76', 'Multiple Choice', '["<", ">", "=", "+"]', '<', 'Medium', ARRAY['Comparison_DirectionConfusion'], 'Student may confuse the direction of comparison signs.', 'Year 2: Understanding comparison symbols.', 'year 2-3'),
('Y3NPV001', 'Number - Number and Place Value', 'Count from 0 in multiples of 4, 8, 50 and 100', 'Count on in 50s from 200. What comes next: 200, 250, 300, __?', 'Multiple Choice', '["350", "400", "320", "500"]', '350', 'Easy', NULL, NULL, 'Year 3: Skip counting by 50s.', 'year 2-3'),
('Y3NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a three-digit number (hundreds, tens, ones)', 'What is the value of the digit 5 in the number 358?', 'Multiple Choice', '["50", "5", "500", "350"]', '50', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify wrong place value (5 for ones or 500 for hundreds).', 'Year 3: Understanding tens place in 3-digit numbers.', 'year 2-3'),
('Y3NPV003', 'Number - Number and Place Value', 'Compare and order numbers up to 1000', 'Order these numbers from smallest to largest: 567, 576, 657', 'Multiple Choice', '["567, 576, 657", "576, 567, 657", "657, 576, 567", "567, 657, 576"]', '567, 576, 657', 'Medium', ARRAY['Ordering_DigitConfusion'], 'Student may focus on individual digits rather than place value.', 'Year 3: Ordering 3-digit numbers.', 'year 2-3'),
('Y2ASM002', 'Number - Addition and Subtraction', 'Recall and use addition and subtraction facts to 20 fluently', 'What is 17 - 9?', 'Multiple Choice', '["8", "7", "6", "9"]', '8', 'Medium', ARRAY['Subtraction_CountingError'], 'Student may make a counting error when subtracting across 10.', 'Year 2: Fluency with facts crossing 10.', 'year 2-3'),
('Y3ASM001', 'Number - Addition and Subtraction', 'Add and subtract numbers mentally, including a three-digit number and ones', 'What is 345 + 7?', 'Multiple Choice', '["352", "342", "452", "315"]', '352', 'Easy', NULL, NULL, 'Year 3: Mental addition with 3-digit numbers.', 'year 2-3'),
('Y3ASM002', 'Number - Addition and Subtraction', 'Add and subtract numbers with up to three digits, using formal written methods', 'Calculate: 456 - 178', 'Multiple Choice', '["278", "378", "268", "288"]', '278', 'Hard', ARRAY['Subtraction_BorrowingError'], 'Student may make errors when borrowing across columns.', 'Year 3: Column subtraction with borrowing.', 'year 2-3'),
('Y3ASM003', 'Number - Addition and Subtraction', 'Solve problems, including missing number problems', '__ + 45 = 82. What is the missing number?', 'Multiple Choice', '["37", "127", "47", "27"]', '37', 'Medium', ARRAY['MissingNumber_OperationError'], 'Student may add instead of subtract (45+82=127).', 'Year 3: Inverse operations for missing numbers.', 'year 2-3'),
('Y2MD001', 'Number - Multiplication and Division', 'Recall and use multiplication and division facts for the 2, 5 and 10 multiplication tables', 'What is 5 × 4?', 'Multiple Choice', '["20", "9", "15", "25"]', '20', 'Easy', ARRAY['Multiplication_AdditionConfusion'], 'Student may add instead of multiply (5+4=9).', 'Year 2: Basic multiplication fact from 5 times table.', 'year 2-3'),
('Y2MD002', 'Number - Multiplication and Division', 'Solve problems involving multiplication and division, using arrays', 'There are 3 rows of apples with 5 apples in each row. How many apples are there altogether?', 'Multiple Choice', '["15", "8", "12", "20"]', '15', 'Medium', ARRAY['Array_AdditionError'], 'Student may add rows and items (3+5=8) instead of multiplying.', 'Year 2: Array representation of multiplication.', 'year 2-3'),
('Y3MD001', 'Number - Multiplication and Division', 'Recall and use multiplication and division facts for the 3, 4 and 8 multiplication tables', 'What is 8 × 3?', 'Multiple Choice', '["24", "21", "32", "11"]', '24', 'Medium', ARRAY['Multiplication_NearbyFact'], 'Student may confuse with 7×3=21 or add 8+3=11.', 'Year 3: Multiplication facts for 8 times table.', 'year 2-3'),
('Y3MD002', 'Number - Multiplication and Division', 'Write and calculate mathematical statements for multiplication using the tables they know', 'Calculate: 4 × 12', 'Multiple Choice', '["48", "16", "44", "52"]', '48', 'Hard', ARRAY['Multiplication_PartialProduct'], 'Student may only multiply 4×2=8 and miss the tens.', 'Year 3: Two-digit multiplication using known facts.', 'year 2-3'),
('Y3MD003', 'Number - Multiplication and Division', 'Solve problems, including positive integer scaling problems', 'Tom has 5 marbles. Sam has 3 times as many. How many marbles does Sam have?', 'Multiple Choice', '["15", "8", "3", "20"]', '15', 'Medium', ARRAY['Scaling_AdditionError'], 'Student may add instead of multiply (5+3=8).', 'Year 3: Understanding scaling in word problems.', 'year 2-3'),
('Y2FR001', 'Number - Fractions', 'Recognise, find, name and write fractions 1/3, 1/4, 2/4 and 3/4', 'What fraction of this shape is shaded? [Imagine a rectangle divided into 4 equal parts with 3 parts shaded]', 'Multiple Choice', '["3/4", "1/4", "1/3", "4/3"]', '3/4', 'Medium', ARRAY['Fraction_InvertedReading'], 'Student may confuse numerator and denominator positions.', 'Year 2: Visual fraction identification.', 'year 2-3'),
('Y2FR002', 'Number - Fractions', 'Write simple fractions and recognise equivalence', 'Which fraction is the same as 1/2?', 'Multiple Choice', '["2/4", "1/4", "3/4", "1/3"]', '2/4', 'Hard', ARRAY['Equivalence_NotRecognized'], 'Student may not recognize that 2/4 equals 1/2.', 'Year 2: Basic equivalent fractions.', 'year 2-3'),
('Y3FR001', 'Number - Fractions', 'Count up and down in tenths', 'What is 3/10 + 2/10?', 'Multiple Choice', '["5/10", "5/20", "1/10", "6/10"]', '5/10', 'Easy', ARRAY['Fractions_DenominatorAddition'], 'Student may incorrectly add denominators (10+10=20).', 'Year 3: Adding tenths.', 'year 2-3'),
('Y3FR002', 'Number - Fractions', 'Recognise and show, using diagrams, equivalent fractions with small denominators', 'Which fraction is equivalent to 2/3?', 'Multiple Choice', '["4/6", "2/6", "3/4", "1/3"]', '4/6', 'Medium', ARRAY['Equivalence_ScalingError'], 'Student may not scale both numerator and denominator correctly.', 'Year 3: Finding equivalent fractions.', 'year 2-3'),
('Y3FR003', 'Number - Fractions', 'Add and subtract fractions with the same denominator within one whole', 'Calculate: 5/7 - 2/7', 'Multiple Choice', '["3/7", "3/14", "7/7", "2/7"]', '3/7', 'Medium', ARRAY['Fractions_DenominatorOperation'], 'Student may incorrectly operate on denominators.', 'Year 3: Subtracting fractions with same denominator.', 'year 2-3'),
('Y3FR004', 'Number - Fractions', 'Compare and order unit fractions, and fractions with the same denominators', 'Which is larger: 1/3 or 1/5?', 'Multiple Choice', '["1/3", "1/5", "They are equal", "Cannot tell"]', '1/3', 'Hard', ARRAY['UnitFraction_DenominatorConfusion'], 'Student may think larger denominator means larger fraction.', 'Year 3: Comparing unit fractions.', 'year 2-3'),
('Y2ME001', 'Measurement', 'Choose and use appropriate standard units to estimate and measure length/height', 'Which unit would you use to measure the length of a pencil?', 'Multiple Choice', '["centimetres", "metres", "kilometres", "hours"]', 'centimetres', 'Easy', ARRAY['Unit_InappropriateChoice'], 'Student may choose an inappropriate unit like metres for small objects.', 'Year 2: Choosing appropriate measurement units.', 'year 2-3'),
('Y2ME002', 'Measurement', 'Recognise and use symbols for pounds (£) and pence (p)', 'How much money is £2 and 50p altogether?', 'Multiple Choice', '["£2.50", "£2.05", "£52", "£250"]', '£2.50', 'Medium', ARRAY['Money_DecimalPlacement'], 'Student may write £2.05 instead of £2.50 for 50p.', 'Year 2: Combining pounds and pence.', 'year 2-3'),
('Y2ME003', 'Measurement', 'Tell and write the time to five minutes, including quarter past/to', 'What time is quarter past 3?', 'Multiple Choice', '["3:15", "3:45", "3:30", "3:05"]', '3:15', 'Medium', ARRAY['Time_QuarterConfusion'], 'Student may confuse quarter past with quarter to (3:45).', 'Year 2: Understanding quarter past notation.', 'year 2-3'),
('Y3ME001', 'Measurement', 'Measure, compare, add and subtract: lengths (m/cm/mm)', 'How many millimetres are in 3 centimetres?', 'Multiple Choice', '["30", "3", "300", "10"]', '30', 'Medium', ARRAY['Conversion_FactorError'], 'Student may use wrong conversion factor or forget to multiply.', 'Year 3: Converting between metric units.', 'year 2-3'),
('Y3ME002', 'Measurement', 'Measure the perimeter of simple 2-D shapes', 'A square has sides of 5cm. What is its perimeter?', 'Multiple Choice', '["20cm", "25cm", "10cm", "15cm"]', '20cm', 'Medium', ARRAY['Perimeter_AreaConfusion'], 'Student may calculate area (25cm²) instead of perimeter.', 'Year 3: Calculating perimeter of regular shapes.', 'year 2-3'),
('Y3ME003', 'Measurement', 'Tell and write the time from an analogue clock, including using Roman numerals', 'A clock shows the Roman numeral IX. What number is this?', 'Multiple Choice', '["9", "11", "4", "6"]', '9', 'Medium', ARRAY['RomanNumerals_AdditionError'], 'Student may add I and X (1+10=11) instead of subtracting.', 'Year 3: Reading Roman numerals on clocks.', 'year 2-3'),
('Y3ME004', 'Measurement', 'Add and subtract amounts of money to give change', 'You buy a toy for £3.45 and pay with £5. How much change do you get?', 'Multiple Choice', '["£1.55", "£2.55", "£1.45", "£8.45"]', '£1.55', 'Hard', ARRAY['Money_SubtractionError'], 'Student may make errors when subtracting with decimals.', 'Year 3: Calculating change with money.', 'year 2-3'),
('Y2GS001', 'Geometry - Properties of Shapes', 'Identify and describe properties of 2-D shapes, including number of sides', 'How many sides does a triangle have?', 'Multiple Choice', '["3", "4", "5", "6"]', '3', 'Easy', NULL, NULL, 'Year 2: Basic shape property identification.', 'year 2-3'),
('Y2GS002', 'Geometry - Properties of Shapes', 'Identify and describe properties of 3-D shapes, including number of edges, vertices and faces', 'How many faces does a cube have?', 'Multiple Choice', '["6", "4", "8", "12"]', '6', 'Medium', ARRAY['3DShape_PropertyConfusion'], 'Student may confuse faces with vertices (8) or edges (12).', 'Year 2: 3D shape properties.', 'year 2-3'),
('Y3GS001', 'Geometry - Properties of Shapes', 'Draw 2-D shapes and make 3-D shapes using modelling materials', 'How many edges does a cube have?', 'Multiple Choice', '["12", "6", "8", "4"]', '12', 'Medium', ARRAY['3DShape_EdgeFaceConfusion'], 'Student may confuse edges with faces (6) or vertices (8).', 'Year 3: Properties of 3D shapes.', 'year 2-3'),
('Y3GS002', 'Geometry - Properties of Shapes', 'Recognise angles as a property of shape or a description of a turn', 'How many right angles are in a complete turn?', 'Multiple Choice', '["4", "2", "3", "1"]', '4', 'Medium', ARRAY['Angle_TurnConfusion'], 'Student may think of half turn (2 right angles) instead of full turn.', 'Year 3: Understanding angles and turns.', 'year 2-3'),
('Y3GS003', 'Geometry - Properties of Shapes', 'Identify horizontal and vertical lines and pairs of perpendicular and parallel lines', 'What do we call two lines that never meet?', 'Multiple Choice', '["Parallel", "Perpendicular", "Vertical", "Diagonal"]', 'Parallel', 'Medium', ARRAY['Lines_TermConfusion'], 'Student may confuse parallel with perpendicular (lines that meet at right angles).', 'Year 3: Understanding line relationships.', 'year 2-3'),
('Y2PD001', 'Geometry - Position and Direction', 'Use mathematical vocabulary to describe position, direction and movement', 'If you turn a quarter turn clockwise from facing North, which direction will you face?', 'Multiple Choice', '["East", "West", "South", "North"]', 'East', 'Hard', ARRAY['Direction_ClockwiseConfusion'], 'Student may turn anticlockwise instead, facing West.', 'Year 2: Understanding clockwise quarter turns.', 'year 2-3'),
('Y2PD002', 'Geometry - Position and Direction', 'Order and arrange combinations of mathematical objects in patterns and sequences', 'What comes next in this pattern: circle, square, circle, square, circle, __?', 'Multiple Choice', '["square", "circle", "triangle", "rectangle"]', 'square', 'Easy', NULL, NULL, 'Year 2: Basic pattern recognition.', 'year 2-3'),
('Y2ST001', 'Statistics', 'Interpret and construct simple pictograms, tally charts, block diagrams', 'In a pictogram where each picture represents 2 children, how many children do 3 pictures represent?', 'Multiple Choice', '["6", "3", "5", "2"]', '6', 'Medium', ARRAY['Pictogram_ScaleError'], 'Student may count pictures (3) instead of applying the scale.', 'Year 2: Understanding pictogram scales.', 'year 2-3'),
('Y3ST001', 'Statistics', 'Interpret and present data using bar charts, pictograms and tables', 'A bar chart shows 8 children like football and 5 like tennis. How many children were surveyed in total?', 'Multiple Choice', '["13", "3", "8", "40"]', '13', 'Easy', ARRAY['Statistics_DifferenceError'], 'Student may find difference (3) instead of total.', 'Year 3: Adding data values from bar charts.', 'year 2-3'),
('Y3ST002', 'Statistics', 'Solve one-step and two-step questions using information presented in scaled bar charts', 'In a bar chart where each square represents 5 people, a bar reaches 4 squares high. How many people does this represent?', 'Multiple Choice', '["20", "4", "9", "15"]', '20', 'Medium', ARRAY['BarChart_ScaleError'], 'Student may count squares (4) without applying scale, or add (4+5=9).', 'Year 3: Understanding scaled bar charts.', 'year 2-3')

ON CONFLICT (question_id) DO NOTHING;

-- Now restore additional Year 4-5 questions
INSERT INTO curriculum (
  question_id, topic, subtopic, example_question, question_type, 
  options, correct_answer, difficulty, red_herring_tag, 
  red_herring_explanation, pedagogical_notes, age_group
) VALUES 
('Y4NPV001', 'Number - Number and Place Value', 'Count in multiples of 6, 7, 9, 25 and 1000', 'Count on in 25s from 150. What comes next: 150, 175, 200, __?', 'Multiple Choice', '["225", "250", "215", "300"]', '225', 'Easy', NULL, NULL, 'Year 4: Skip counting by 25s.', 'year 4-5'),
('Y4NPV002', 'Number - Number and Place Value', 'Recognise the place value of each digit in a four-digit number', 'What is the value of the digit 7 in the number 3,746?', 'Multiple Choice', '["700", "7", "70", "7000"]', '700', 'Medium', ARRAY['PlaceValue_PositionError'], 'Student may identify the wrong place value position (70 for tens or 7 for ones).', 'Year 4: Understanding hundreds place in 4-digit numbers.', 'year 4-5'),
('Y4NPV003', 'Number - Number and Place Value', 'Count backwards through zero to include negative numbers', 'Continue the sequence: 3, 1, -1, __', 'Multiple Choice', '["-3", "-2", "0", "-4"]', '-3', 'Medium', ARRAY['NegativeNumbers_PatternError'], 'Student may not recognize the pattern of subtracting 2 each time.', 'Year 4: Counting backwards through zero.', 'year 4-5'),
('Y4NPV004', 'Number - Number and Place Value', 'Round any number to the nearest 10, 100 or 1000', 'Round 4,567 to the nearest hundred.', 'Multiple Choice', '["4,600", "4,500", "4,570", "5,000"]', '4,600', 'Medium', ARRAY['Rounding_DirectionError'], 'Student may round down to 4,500 instead of up to 4,600.', 'Year 4: Rounding to nearest hundred.', 'year 4-5'),
('Y5NPV001', 'Number - Number and Place Value', 'Read, write, order and compare numbers to at least 1,000,000', 'Which number is larger: 456,789 or 456,879?', 'Multiple Choice', '["456,879", "456,789", "They are equal", "Cannot tell"]', '456,879', 'Medium', ARRAY['LargeNumber_DigitPositionError'], 'Student may compare wrong place values in large numbers.', 'Year 5: Comparing 6-digit numbers.', 'year 4-5'),
('Y5NPV002', 'Number - Number and Place Value', 'Count forwards or backwards in steps of powers of 10', 'What is 34,500 + 1,000?', 'Multiple Choice', '["35,500", "34,600", "44,500", "34,510"]', '35,500', 'Easy', ARRAY['PowersOf10_PlaceValueError'], 'Student may add to wrong place value column.', 'Year 5: Adding powers of 10.', 'year 4-5'),
('Y5NPV003', 'Number - Number and Place Value', 'Interpret negative numbers in context, count forwards and backwards with positive and negative whole numbers', 'The temperature is -5°C. It rises by 8°C. What is the new temperature?', 'Multiple Choice', '["3°C", "-13°C", "13°C", "-3°C"]', '3°C', 'Medium', ARRAY['NegativeNumbers_OperationError'], 'Student may subtract instead of add (-5-8=-13) or mishandle crossing zero.', 'Year 5: Working with negative numbers in context.', 'year 4-5'),
('Y5NPV004', 'Number - Number and Place Value', 'Round any number up to 1,000,000 to the nearest 10, 100, 1000, 10,000 and 100,000', 'Round 654,321 to the nearest 10,000.', 'Multiple Choice', '["650,000", "660,000", "654,000", "700,000"]', '650,000', 'Hard', ARRAY['Rounding_LargePlaceValue'], 'Student may round to wrong place value or round up incorrectly.', 'Year 5: Rounding large numbers to ten thousands.', 'year 4-5'),
('Y4ASM001', 'Number - Addition and Subtraction', 'Add and subtract numbers with up to 4 digits using formal written methods', 'Calculate: 3,456 + 1,789', 'Multiple Choice', '["5,245", "4,245", "5,235", "5,145"]', '5,245', 'Medium', ARRAY['Addition_CarryingError'], 'Student may make errors when carrying over between columns.', 'Year 4: 4-digit addition with carrying.', 'year 4-5'),
('Y4ASM002', 'Number - Addition and Subtraction', 'Solve addition and subtraction two-step problems in contexts', 'A school had 1,234 books. They bought 256 more books and then gave away 189 books. How many books do they have now?', 'Multiple Choice', '["1,301", "1,679", "1,290", "1,401"]', '1,301', 'Hard', ARRAY['MultiStep_SequenceError'], 'Student may add all numbers (1,679) instead of adding then subtracting.', 'Year 4: Two-step word problem with addition and subtraction.', 'year 4-5')

ON CONFLICT (question_id) DO NOTHING;